#!/bin/bash
# Tillerstead Git Commit Guide – Modern Theme Update
# Compliant with TCNA 2024, NJ HIC, and project OUTPUT_RULES.md

echo "🔍 Git Status (TCNA/NJ HIC Compliance Check)"
git status

echo ""
echo "🆕 New SCSS Modules (TCNA-compliant, accessible, modular):"
echo "  • assets/css/main.scss                # Primary stylesheet (HTML5/CSS3, WCAG 2.1)"
echo "  • _sass/base/_reset.scss              # Standards-based CSS reset"
echo "  • _sass/base/_typography.scss         # Accessible typography system"
echo "  • _sass/layout/_container.scss        # Responsive container utilities"
echo "  • _sass/layout/_grid.scss             # TCNA grid system (updated for clarity)"
echo "  • _sass/components/_buttons.scss      # Accessible button components"
echo "  • _sass/components/_cards.scss        # Card UI components"
echo "  • _sass/components/_forms.scss        # Form elements (labelled, ARIA-ready)"
echo "  • _sass/components/_header.scss       # Header & navigation (semantic, keyboard-nav)"
echo "  • _sass/components/_footer.scss       # Footer (contact, NJ HIC info)"
echo "  • _sass/components/_hero.scss         # Hero sections (conversion-focused)"
echo "  • _sass/utilities/_helpers.scss       # Utility classes (updated, descriptive)"
echo ""
echo "🛠️  Updated Files:"
echo "  • package.json                        # npm scripts (lint, build, accessibility)"
echo "  • assets/css/main-build.scss → main.scss  # Renamed for OUTPUT_RULES.md compliance"
echo "  • Documentation (.md)                 # Updated for TCNA/NJ HIC, accessibility"
echo ""
echo "🗑️  Deprecated/Obsolete Files (remove for technical debt elimination):"
echo "  • assets/css/main-build.scss          # Superseded by main.scss"
echo "  • src/scss/                           # Legacy, non-compliant directory"
echo "  • src/assets/                         # Legacy, non-compliant directory"
echo ""
echo "✅ Staging Instructions (per OUTPUT_RULES.md):"
echo "  git add ."
echo ""
echo "💬 Commit Example (clear, descriptive, compliant):"
echo "  git commit -m \"Refactor: TCNA-compliant modern theme, HTML5/CSS3, accessibility upgrades\""
echo ""
echo "🔎 Selective Staging (for granular compliance):"
echo "  git add _sass/"
echo "  git add assets/css/main.scss"
echo "  git add package.json"
echo "  git add *.md"
echo ""
echo "🔗 Ensure all references, alt text, and legal attributions are present (see _data/compliance.yml)"
echo ""
echo "🧪 Validate before push:"
echo "  npm run lint         # ESLint, stylelint"
echo "  bundle exec jekyll build --strict_front_matter"
echo "  npm run test:a11y    # Accessibility checks"
echo ""
echo "📋 All changes must pass: HTMLHint, ESLint, Jekyll build, accessibility/performance targets."
echo ""
echo "For detailed standards, see /.ai/OUTPUT_RULES.md and /.ai/COMPLIANCE.md."
